import {
  FaDatabase,
  FaEnvelope,
  FaFacebook,
  FaGithub,
  FaInstagram,
  FaJava,
  FaKey,
  FaLinkedin,
  FaMapMarkerAlt,
  FaPhone,
  FaShieldAlt,
} from "react-icons/fa";
import {
  SiApachekafka,
  SiCss3,
  SiDocker,
  SiGit,
  SiGithubactions,
  SiHtml5,
  SiJavascript,
  SiMysql,
  SiPostgresql,
  SiPython,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiSpring,
  SiTailwindcss,
  SiAmazonwebservices,
} from "react-icons/si";

export const socialIcons = {
  facebook: FaFacebook,
  github: FaGithub,
  instagram: FaInstagram,
  linkedin: FaLinkedin,
};

export const skillIcons = {
  Java: FaJava,
  Python: SiPython,
  JavaScript: SiJavascript,
  HTML5: SiHtml5,
  SQL: FaDatabase,
  "Spring Boot 3": SiSpring,
  "Spring Security": FaShieldAlt,
  "REST APIs": FaKey,
  "JWT Authentication": FaKey,
  OAuth2: FaShieldAlt,
  Redis: SiRedis,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  Docker: SiDocker,
  RabbitMQ: SiRabbitmq,
  Kafka: SiApachekafka,
  React: SiReact,
  "Tailwind CSS": SiTailwindcss,
  HTML: SiHtml5,
  CSS: SiCss3,
  Git: SiGit,
  "GitHub Actions": SiGithubactions,
  AWS: SiAmazonwebservices,
};

export const skillColors = {
  Java: "#f89820",
  Python: "#3776ab",
  JavaScript: "#f7df1e",
  HTML5: "#e34f26",
  SQL: "#336791",
  "Spring Boot 3": "#6db33f",
  "Spring Security": "#6db33f",
  "REST APIs": "#009688",
  "JWT Authentication": "#fb015b",
  OAuth2: "#eb5424",
  Redis: "#dc382d",
  PostgreSQL: "#336791",
  MySQL: "#4479a1",
  Docker: "#2496ed",
  RabbitMQ: "#ff6600",
  Kafka: "#e0e0e0",
  React: "#61dafb",
  "Tailwind CSS": "#06b6d4",
  HTML: "#e34f26",
  CSS: "#1572b6",
  Git: "#f05032",
  "GitHub Actions": "#2088ff",
  AWS: "#ff9900",
};

export const contactIcons = {
  email: FaEnvelope,
  linkedin: FaLinkedin,
  location: FaMapMarkerAlt,
  phone: FaPhone,
};
